### ISSUE TITLE
ECDSA deployment

### ISSUE THREAD

**Issue by rijswijk** [Deploy360/state-of-dnssec-deployment#1]
Hi Dan,

Here are pointers to some recent work on ECDSA deployment:

paper:
http://wwwhome.ewi.utwente.nl/~rijswijkrm/pub/cnsm2016-ecdsa.pdf

poster:
http://wwwhome.ewi.utwente.nl/~rijswijkrm/pub/cnsm2016-poster.pdf

If desired, can provide updated graphs & stats.

Cheers,

Roland

**Comment by danyork** [comment]
Many thanks!

**Comment by danyork** [comment]
Links incorporated into 2016 document. Note that for the 2017 version we should find out if there are updated numbers.
